"""add vision_tests client_id tested_at index

Revision ID: bc3feb762a30
Revises: 0005_owner_admin_flow
Create Date: 2026-03-20 20:38:47.457866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc3feb762a30'
down_revision: Union[str, None] = '0005_owner_admin_flow'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_login_verification_codes_id'), 'login_verification_codes', ['id'], unique=False)
    op.drop_constraint(op.f('telegram_pending_links_start_token_key'), 'telegram_pending_links', type_='unique')
    op.create_index(op.f('ix_telegram_pending_links_id'), 'telegram_pending_links', ['id'], unique=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_vision_tests_client_id_tested_at', 'vision_tests', ['client_id', 'tested_at'], unique=False)
    op.create_index(op.f('ix_vision_tests_id'), 'vision_tests', ['id'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_vision_tests_id'), table_name='vision_tests')
    op.drop_index('ix_vision_tests_client_id_tested_at', table_name='vision_tests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_telegram_pending_links_id'), table_name='telegram_pending_links')
    op.create_unique_constraint(op.f('telegram_pending_links_start_token_key'), 'telegram_pending_links', ['start_token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_login_verification_codes_id'), table_name='login_verification_codes')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    # ### end Alembic commands ###

